<?php

namespace eventBundle\Repository;

/**
 * commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function find_com_sujet($idev){
        $query=$this->getEntityManager()
            ->createQuery("select n from eventBundle:commentaire n where n.idSujet= '$idev' ");
        return $query->getResult();

    }

}
