<?php

namespace eventBundle\Repository;

/**
 * inscription_packRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscription_packRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderedBydate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM eventBundle:inscription_pack p ORDER BY p.dateInsc DESC '
            )
            ->getResult();
    }

    function Searchinscri($libelle){
        $query=$this->getEntityManager()->createQuery("select e from eventBundle:inscription_pack e where e.idPack.titre LIKE '%$libelle%'");
        return $query->getResult();

    }
    function Search1inscri($libelle){
        $query=$this->getEntityManager()->createQuery(" select i.id,i.titre, u.id,u.nom, u.prenom, e.idInscription, e.dateInsc 
image                                            FROM eventBundle:pack i,   eventBundle:enfant u ,  eventBundle:inscription_pack e 
                                              WHERE i.id=e.idPack and u.id=e.idEnfant and  i.titre LIKE '%$libelle%'");
        return $query->getResult();
    }


}
