<?php

namespace eventBundle\Repository;

/**
 * inscription_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscription_evenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function find_event_inscr($idev){
        $query=$this->getEntityManager()
            ->createQuery("select n from eventBundle:inscription_evenement n where n.id_event= '$idev' ORDER BY n.dateInsc DESC");
        return $query->getResult();

    }

    public function findAllorder(){
        $query=$this->getEntityManager()
            ->createQuery("select n from eventBundle:inscription_evenement n   
            ORDER BY n.dateInsc DESC");
        return $query->getResult();

    }

    function Searchinscri($libelle){
        $query=$this->getEntityManager()->createQuery("select e from eventBundle:inscription_evenement e where e.dateInsc LIKE '%$libelle%'");
        return $query->getResult();

    }

    public function findAllEnforder($idu){
        $query=$this->getEntityManager()
            ->createQuery("select n from eventBundle:inscription_evenement n,eventBundle:enfant z
             where n.id_enfant=z.id
             and z.idParent= '$idu'
            ORDER BY n.dateInsc DESC");
        return $query->getResult();

    }





}
