<?php

namespace eventBundle\Repository;

/**
 * inscription_cantineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscription_cantineRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllOrderedBydate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM eventBundle:inscription_cantine p ORDER BY p.dateInsc DESC '
            )
            ->getResult();
    }

    function Searchinscri($libelle){
        $query=$this->getEntityManager()->createQuery("select e from eventBundle:inscription_cantine e where e.dateInsc LIKE '%$libelle%'");
        return $query->getResult();

    }

}
