<?php

namespace eventBundle\Repository;

/**
 * menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menuRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheentre($entre)
    {
        $query=$this->getEntityManager()->createQuery("select c from eventBundle:menu c where c.entre LIKE %'$entre'%");
        return $query->getResult();

    }


    public function findAllOrderedBydate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM eventBundle:menu p ORDER BY p.date DESC '
            )
            ->getResult();
    }


    function SearchMenu($libelle){
        $query=$this->getEntityManager()->createQuery("select e from eventBundle:menu e where e.date LIKE '%$libelle%'");
        return $query->getResult();

    }
}
