<?php

namespace eventBundle\Repository;

/**
 * packRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class packRepository extends \Doctrine\ORM\EntityRepository
{

    public function recherchetype($type)
    {
        $query=$this->getEntityManager()->createQuery("select c from eventBundle:pack c where c.type LIKE %'$type'%");
        return $query->getResult();

    }


    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM eventBundle:pack p ORDER BY p.id DESC '
            )
            ->getResult();
    }

    public function myfindall(){
        $query=$this->getEntityManager()->createQuery(
            "select n from eventBundle:pack n "

        );

        return $query->getResult();
    }

}
