<?php

namespace eventBundle\Repository;

/**
 * sujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sujetRepository extends \Doctrine\ORM\EntityRepository
{

    public function find_com_sujet($idev){
        $query=$this->getEntityManager()
            ->createQuery("select n from eventBundle:commentaire n where n.idSujet= '$idev' ");
        return $query->getResult();

    }


    function Searchinscri($libelle){
        $query=$this->getEntityManager()->createQuery("select e from eventBundle:sujet e where e.date LIKE '%$libelle%'");
        return $query->getResult();

    }
}
